keys:
  - &admin_markus age1r5yppy5uvnen28vwj779dssvhx3qf2qygs727e6fkgr4fjn3gugq3g3dtu
  - &server_pi age15zjs4qzjujfnuzc2mhaq2h3vt2s86dfuuk9uyvdlgsfv9cw53c9svzvl35
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *admin_markus
      - *server_pi
