keys:
  - &admin_markus age10yzfu0yeqmhjq75qq9dqtxalgd2sakmzrw7ukfkznmfjcg8v7u8qfqnxe0
  - &server_pi age15k98fx7s0x2tt942kcd2aj27rstrnfhyxnnwuv89xxhmd7njffequssnlq
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *admin_markus
      - *server_pi
